<?php echo $header; ?>
<main>
	<section class="gyik">
		<div class="container">
			<h1>GYIK</h1>
			<div class="box clear">				
			<h4 class="reg">Frissülj ősszel is a Szentkirályival és játssz velünk!</h4>
			<h4>Hogyan vehetek részt a játékban?</h4>
			<p>A Játékos feladata, hogy a promóció ideje alatt egyszerre vásároljon 12 palack 1,5 literes szénsavas, enyhe vagy szénsavmentes Szentkirályi ásványvizet, és a vásárlást igazoló blokkon található 8 számjegyű AP kódot (pl. A12345678) pedig töltse fel a regisztrációt követően a www.szentkiralyifelfrissules.hu microsite-on található felületre. A regisztráció során meg kell adni: a játékos nevét, e-mail címét, a kódot és a vásárlás időpontját (hónap, nap, óra, perc).</p>
			<h4>Meddig jelentkezhetek a nyereményjátékra?</h4>
			<p>A nyereményjáték 2015. november 19. napján 00 óra 00 perctől – 2015. december 2. napján 23 óra 59 percig tart. A kódok feltöltésének határideje a nyereményjáték utolsó napján, 23 óra 59 perc.</p>
			<h4>Mik a nyeremények és hány alkalommal nyerhetek a promóció során?</h4>
			<h4 class="up">Fődíj:</h4>
			<p class="nop">1 db 3 napos wellness hétvége 2 fő részére a siófoki Hotel Residence Balatonban vagy a mátraházi Hotel Residence Ózonban </p>
			<h4 class="up">Kiemelt nyeremény:</h4>
			<p class="nop">30 db Feldobox kóstoló élménycsomag</p>
			<h4 class="up">További díjak:</h4>
			<p">60 db Tesco ajándékutalvány<br> 
			60 db ásványvíz csomag (csomagonként 6 zsugor (6*6 palack)<br> 
			1,5l-es szénsavmentes Szentkirályi ásványvíz)<br>
			Egy játékos a promóció teljes ideje alatt maximum 3 (három) nyeremény megnyerésére jogosult.
			</p>
			<p>A regisztráció és a kód feltöltése után egy felugró ablakban azonnal megjelenik egy üzenet, amelyből kiderül, szerencsével jártál-e, és ha igen, mit nyertél. Ha nem nyertél, ne keseredj el, egy új kóddal ismét szerencsét próbálhatsz! A fődíjat a promóció végén sorsoljuk, a szerencsés nyertessel pedig e-mailben vesszük fel a kapcsolatot.
			Sorsolás: 2015. december 3-án
			Mit kell tennem, ha nyertem?</p>
			<a href="#" class="btn-blue">Kódfeltöltés</a>
			</div>			
		</div>
	</section>
	<div class="mountain custom-2">
		<div class="theodora-water"></div>
	</div>

</main>
<?php echo $footer; ?>