<!DOCTYPE html>
<html lang="hu">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <title>Theodora</title>

    <meta name="description" content="">

    <!-- Screen CSS -->
    <link href="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/css/screen.css" rel="stylesheet">

    <!-- 3rd-party CSS -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

    <!-- Favicons -->

    <!-- JQuery -->
    <script src="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/js/3rd-party/jquery.min.js"></script>

    <!-- 3rd-party JS files -->
    <script src="https://use.typekit.net/ecn5xfk.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>
    <script src="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/js/3rd-party/jquery.bxslider.min.js"></script>
    <script src="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/js/3rd-party/placeholders.min.js"></script>

    
    <!-- Main JS file -->
    <script src="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/js/main.js"></script>
</head>
<body>
<!--[if lt IE 10]>
   <link href="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/css/ie9fix.css" rel="stylesheet">
<![endif]-->
<!--[if lt IE 9]>
    <p class="browserupgrade"><strong>Elavult</strong> böngészőt használsz. Kérlek <a href="http://browsehappy.com/">tölts le</a> újabb böngészőt, az optimális böngészés érdekében.</p>
<![endif]-->
<header>
    <div class="container">
        <a href="#" class="theodora-logo"></a>
        <button class="mobile-icon">
            <span></span>
            <span></span>
            <span></span>
        </button>
        <nav>
            <ul>
                <li><a class="hash" href="/theodora/">Főoldal</a></li>
                <li><a class="hash" href="/theodora/">Kódfeltöltés</a></li>
                <li><a class="hash" href="/theodora/">Nyeremények</a></li>
                <li><a class="hash" href="#">Játékszabályzat</a></li>
                <li><a class="hash" href="/theodora/gyakran-ismetelt-kerdesek">Gyik</a></li>
            </ul>
        </nav>
        <a href="#" class="lidl-logo"></a>
    </div>
</header>
